# Generated by Django 3.2.4 on 2021-07-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=50, verbose_name='Nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreModelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('patente', models.CharField(max_length=6, verbose_name='Patente')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core2.marca')),
            ],
        ),
    ]
