# Generated by Django 3.2.4 on 2021-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='imagen',
            field=models.CharField(default='', max_length=100),
        ),
    ]
